apiVersion: v1
kind: Service
metadata:
  name: app-service   # App Load balancer
spec:
  selector:
    app: flutter-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Exposed externally
