apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: your-db-image:tag
        ports:
        - containerPort: 5432