apiVersion: v1
kind: Service
metadata:
  name: db-service  # DB Load balancer
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP # Exposed to internal net
