apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flutter-app
    spec:
      containers:
      - name: flutter-app-container
        image: your-flutter-app-image:tag
        ports:
        - containerPort: 80